In [25]:
import numpy as np

In [29]:
integers=np.array([10,20,30,40,50])

In [31]:
integers[0]

10

In [33]:
integers[-1]

50

In [35]:
integers[0]=20
print(integers)

[20 20 30 40 50]


In [37]:
integers[0]=21.5
print(integers)

[21 20 30 40 50]


In [39]:
integers.dtype

dtype('int32')

In [45]:
smallerintegers=np.array(integers,dtype=np.int8)
smallerintegers

array([21, 20, 30, 40, 50], dtype=int8)

In [49]:
intergers.nbytes

NameError: name 'intergers' is not defined

In [51]:
smallerintegers.nbytes

5

In [53]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [55]:
floats.dtype

dtype('float64')