In [1]:
import numpy as np

In [3]:
first_arr=np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [13]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [15]:
second_arr=np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [17]:
new_second_arr=np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [19]:
third_arr=np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [21]:
del_arr=np.delete(third_arr,4)
del_arr

array([1, 2, 3, 4])

In [29]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([ 0,  8, 13,  5, 17,  6,  5, 19,  4, 16,  9, 10, 18, 12, 16, 13, 19,
        3, 14,  5])

In [37]:
print(np.sort(integers_arr))

[ 0  3  4  5  5  5  6  8  9 10 12 13 13 14 16 16 17 18 19 19]


In [39]:
integers_2dim_arr=np.array([[3,2,5,7,4],[5,0,8,3,1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [41]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [45]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [47]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']
